apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysqlRootPassword | quote }}
          - name: MYSQL_DATABASE
            value: {{ .Values.mysqlDatabase | quote }}
          - name: MYSQL_USER
            value: {{ .Values.mysqlUser | quote }}
          - name: MYSQL_PASSWORD
            value: {{ .Values.mysqlPassword | quote }}
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
